const actionTypes = {
  ARTICLE_FETCH: 'ARTICLE_FETCH',
  ARTICLE_FETCH_SUCCESS: 'ARTICLE_FETCH_SUCCESS',
  ARTICLE_FETCH_FAILURE: 'ARTICLE_FETCH_FAILURE',
  ARTICLE_FETCH_CANCEL: 'ARTICLE_FETCH_CANCEL',
  ARTICLE_CLEAR: 'ARTICLE_CLEAR',

  ARTICLELIST_FETCH: 'ARTICLELIST_FETCH',
  ARTICLELIST_FETCH_SUCCESS: 'ARTICLELIST_FETCH_SUCCESS',
  ARTICLELIST_FETCH_FAILURE: 'ARTICLELIST_FETCH_FAILURE',
  ARTICLELIST_FETCH_CANCEL: 'ARTICLELIST_FETCH_CANCEL',

  PUBLICATIONLIST_FETCH: 'PUBLICATIONLIST_FETCH',
  PUBLICATIONLIST_FETCH_SUCCESS: 'PUBLICATIONLIST_FETCH_SUCCESS',
  PUBLICATIONLIST_FETCH_FAILURE: 'PUBLICATIONLIST_FETCH_FAILURE',
  PUBLICATIONLIST_FETCH_CANCEL: 'PUBLICATIONLIST_FETCH_CANCEL',

  AUTOCOMPLETE_FETCH: 'AUTOCOMPLETE_FETCH',
  AUTOCOMPLETE_FETCH_SUCCESS: 'AUTOCOMPLETE_FETCH_SUCCESS',
  AUTOCOMPLETE_FETCH_FAILURE: 'AUTOCOMPLETE_FETCH_FAILURE',
}

export default actionTypes