const constants = {
  ARTICLE_FETCH: 'ARTICLE_FETCH',
  ARTICLE_FETCH_FULFILLED: 'ARTICLE_FETCH_FULFILLED',
  ARTICLE_FETCH_CANCELLED: 'ARTICLE_FETCH_CANCELLED',
  ARTICLE_FETCH_ERROR: 'ARTICLE_FETCH_ERROR',
  ARTICLE_CLEAR: 'ARTICLE_CLEAR',

  ARTICLE_LIST_FETCH: 'ARTICLE_LIST_FETCH',
  ARTICLE_LIST_FETCH_FULFILLED: 'ARTICLE_LIST_FETCH_FULFILLED',
  ARTICLE_LIST_FETCH_CANCELLED: 'ARTICLE_LIST_FETCH_CANCELLED',
  ARTICLE_LIST_FETCH_ERROR: 'ARTICLE_LIST_FETCH_ERROR',

  AUTOCOMPLETE_FETCH: 'AUTOCOMPLETE_FETCH',
  AUTOCOMPLETE_FETCH_FULFILLED: 'AUTOCOMPLETE_FETCH_FULFILLED',
  AUTOCOMPLETE_FETCH_ERROR: 'AUTOCOMPLETE_FETCH_ERROR',

  PUBLICATION_LIST_FETCH: 'PUBLICATION_LIST_FETCH',
  PUBLICATION_LIST_FETCH_FULFILLED: 'PUBLICATION_LIST_FETCH_FULFILLED',
  PUBLICATION_LIST_FETCH_CANCELLED: 'PUBLICATION_LIST_FETCH_CANCELLED',
  PUBLICATION_LIST_FETCH_ERROR: 'PUBLICATION_LIST_FETCH_ERROR',
}

export default constants