const constants = {
  ARTICLE_FETCH: 'ARTICLE_FETCH',
  ARTICLE_FETCH_DONE: 'ARTICLE_FETCH_DONE',
  ARTICLE_FETCH_CANCEL: 'ARTICLE_FETCH_CANCEL',
  ARTICLE_FETCH_ERROR: 'ARTICLE_FETCH_ERROR',
  ARTICLE_CLEAR: 'ARTICLE_CLEAR',

  ARTICLE_LIST_FETCH: 'ARTICLE_LIST_FETCH',
  ARTICLE_LIST_FETCH_DONE: 'ARTICLE_LIST_FETCH_DONE',
  ARTICLE_LIST_FETCH_CANCEL: 'ARTICLE_LIST_FETCH_CANCEL',
  ARTICLE_LIST_FETCH_ERROR: 'ARTICLE_LIST_FETCH_ERROR',

  AUTOCOMPLETE_FETCH: 'AUTOCOMPLETE_FETCH',
  AUTOCOMPLETE_FETCH_DONE: 'AUTOCOMPLETE_FETCH_DONE',
  AUTOCOMPLETE_FETCH_ERROR: 'AUTOCOMPLETE_FETCH_ERROR',

  PUBLICATION_LIST_FETCH: 'PUBLICATION_LIST_FETCH',
  PUBLICATION_LIST_FETCH_DONE: 'PUBLICATION_LIST_FETCH_DONE',
  PUBLICATION_LIST_FETCH_CANCEL: 'PUBLICATION_LIST_FETCH_CANCEL',
  PUBLICATION_LIST_FETCH_ERROR: 'PUBLICATION_LIST_FETCH_ERROR',
}

export default constants