export const ARTICLE_FETCH = 'ARTICLE_FETCH'
export const ARTICLE_FETCH_FULFILLED = 'ARTICLE_FETCH_FULFILLED'
export const ARTICLE_FETCH_CANCELLED = 'ARTICLE_FETCH_CANCELLED'
export const ARTICLE_FETCH_ERROR = 'ARTICLE_FETCH_ERROR'
export const ARTICLE_CLEAR = 'ARTICLE_CLEAR'

export const ARTICLE_LIST_FETCH = 'ARTICLE_LIST_FETCH'
export const ARTICLE_LIST_FETCH_FULFILLED = 'ARTICLE_LIST_FETCH_FULFILLED'
export const ARTICLE_LIST_FETCH_CANCELLED = 'ARTICLE_LIST_FETCH_CANCELLED'
export const ARTICLE_LIST_FETCH_ERROR = 'ARTICLE_LIST_FETCH_ERROR'

export const AUTOCOMPLETE_FETCH = 'AUTOCOMPLETE_FETCH'
export const AUTOCOMPLETE_FETCH_FULFILLED = 'AUTOCOMPLETE_FETCH_FULFILLED'
export const AUTOCOMPLETE_FETCH_ERROR = 'AUTOCOMPLETE_FETCH_ERROR'

export const PUBLICATION_LIST_FETCH = 'PUBLICATION_LIST_FETCH'
export const PUBLICATION_LIST_FETCH_FULFILLED = 'PUBLICATION_LIST_FETCH_FULFILLED'
export const PUBLICATION_LIST_FETCH_CANCELLED = 'PUBLICATION_LIST_FETCH_CANCELLED'
export const PUBLICATION_LIST_FETCH_ERROR = 'PUBLICATION_LIST_FETCH_ERROR'
